version: '3.8'

services:
  app:
    build: ./project
    image: node_app:latest
    container_name: node_app
    volumes:
      - ./project:/app  
    ports: 
      - '6006:6006'
    depends_on: 
      - mongo

  mongo: 
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo_data:/data/db  
    ports: 
      - '27017:27017'

volumes:
  mongo_data:  
